import { RADIUS } from "./constants.js";

export const chapters = [
  { id: 1, name: "Arrival", line: "The chamber wakes when you do." },
  { id: 2, name: "Calibration", line: "Some plates answer only to a trace." },
  { id: 3, name: "Echo Chambers", line: "A door can exist for a moment, then forget you." },
  { id: 4, name: "Momentum Labs", line: "Speed is a material here." },
  { id: 5, name: "Chorus", line: "The machine can hold more than one past." },
  { id: 6, name: "Synchrony", line: "Together, or not at all." },
  { id: 7, name: "Contact", line: "An echo has weight, if you let it." },
  { id: 8, name: "Paradox Wing", line: "Change the first note, and the song changes." },
  { id: 9, name: "The Core", line: "Time is not a corridor. It is a chord." },
];

const W = 1280;
const H = 720;

function shell() {
  return [
    { id: "ceil", x: 0, y: 0, w: W, h: 28 },
    { id: "wall-l", x: 0, y: 0, w: 28, h: H },
    { id: "wall-r", x: W - 28, y: 0, w: 28, h: H },
  ];
}

function restY(floorTop) {
  return floorTop - RADIUS;
}

function hints(...lines) {
  return lines;
}

export const levels = [
  {
    id: "first-bounce",
    name: "First Bounce",
    chapter: 1,
    objective: "Reach the aperture.",
    caption: "Steer. The ball does the bouncing.",
    echoSeconds: 20,
    maxGhosts: 0,
    par: { ghosts: 0, seconds: 8 },
    spawn: { x: 140, y: restY(640) },
    ghostSolid: false,
    solids: [
      ...shell(),
      { id: "floor-a", x: 0, y: 640, w: 520, h: 80 },
      { id: "spring", x: 520, y: 640, w: 150, h: 80, surface: "spring", launch: 760 },
      { id: "floor-b", x: 670, y: 640, w: 610, h: 80 },
    ],
    doors: [],
    plates: [],
    movers: [],
    hazards: [],
    goal: { x: 1060, y: 430, w: 160, h: 210 },
    plaques: [{ x: 540, y: 600, text: "HOP" }],
    hints: hints(
      "The aperture is the glowing ring on the right.",
      "Hold right. You do not need a jump button.",
      "The copper pad will toss you. You still land on the floor.",
      "Keep going right until the ring takes you.",
      "Hold right from the start and stay on the floor until you reach the ring."
    ),
  },
  {
    id: "keep-the-door",
    name: "Keep the Door",
    chapter: 1,
    objective: "Open the door with a version of yourself.",
    caption: "Stand on the plate, then Echo. That was you.",
    echoSeconds: 16,
    maxGhosts: 1,
    par: { ghosts: 1, seconds: 10 },
    spawn: { x: 120, y: restY(640) },
    ghostSolid: false,
    solids: [...shell(), { id: "floor", x: 0, y: 640, w: W, h: 80 }],
    doors: [{ id: "d1", x: 800, y: 28, w: 40, h: 612, logic: "or" }],
    plates: [
      { id: "p1", x: 340, y: 584, w: 170, h: 56, targets: ["d1"], mode: "hold", who: "any" },
    ],
    movers: [],
    hazards: [],
    goal: { x: 1040, y: 500, w: 150, h: 140 },
    plaques: [{ x: 360, y: 548, text: "HOLD" }],
    hints: hints(
      "The plate is wired to the door.",
      "The door stays open only while something is on the plate.",
      "You cannot hold the plate and walk through the door.",
      "Echo while you are standing on the plate. Your ghost will return to it.",
      "Stop on the gold plate, press Echo, then wait by the door until your ghost holds it."
    ),
  },
  {
    id: "leave-yourself",
    name: "Leave Yourself",
    chapter: 1,
    objective: "Leave an echo in the pit.",
    caption: "Hold down on a grate to drop through it.",
    echoSeconds: 16,
    maxGhosts: 1,
    par: { ghosts: 1, seconds: 12 },
    spawn: { x: 110, y: restY(500) },
    ghostSolid: false,
    solids: [
      ...shell(),
      { id: "left", x: 0, y: 500, w: 240, h: 220 },
      { id: "grate-p1", x: 240, y: 500, w: 150, h: 30, grate: true },
      { id: "right", x: 390, y: 500, w: 890, h: 220 },
      { id: "pit", x: 240, y: 688, w: 150, h: 32 },
    ],
    doors: [{ id: "d1", x: 860, y: 28, w: 40, h: 472, logic: "or" }],
    plates: [
      { id: "p1", x: 252, y: 634, w: 126, h: 56, targets: ["d1"], mode: "hold", who: "any" },
    ],
    movers: [],
    hazards: [],
    goal: { x: 1060, y: 390, w: 140, h: 110 },
    plaques: [{ x: 250, y: 468, text: "DROP" }],
    hints: hints(
      "The grate is a choice. You can roll over it, or fall through.",
      "The plate in the pit is what the door is listening to.",
      "Hold down while you are on the grate.",
      "Echo after you land. Next time, do not drop. Roll over the grate.",
      "Drop onto the plate, Echo, then roll across the grate and through the door while your ghost stays below."
    ),
  },
  {
    id: "handoff",
    name: "Handoff",
    chapter: 1,
    objective: "Two doors. Two echoes.",
    caption: "Each echo can only be in one place.",
    echoSeconds: 18,
    maxGhosts: 2,
    par: { ghosts: 2, seconds: 12 },
    spawn: { x: 90, y: restY(500) },
    ghostSolid: false,
    solids: [
      ...shell(),
      { id: "a", x: 0, y: 500, w: 190, h: 220 },
      { id: "grate-p1", x: 190, y: 500, w: 130, h: 30, grate: true },
      { id: "b", x: 320, y: 500, w: 210, h: 220 },
      { id: "grate-p2", x: 530, y: 500, w: 130, h: 30, grate: true },
      { id: "c", x: 660, y: 500, w: 620, h: 220 },
      { id: "pit1", x: 190, y: 688, w: 130, h: 32 },
      { id: "pit2", x: 530, y: 688, w: 130, h: 32 },
    ],
    doors: [
      { id: "d1", x: 400, y: 28, w: 36, h: 472, logic: "or" },
      { id: "d2", x: 900, y: 28, w: 36, h: 472, logic: "or" },
    ],
    plates: [
      { id: "p1", x: 200, y: 634, w: 110, h: 56, targets: ["d1"], mode: "hold", who: "any" },
      { id: "p2", x: 540, y: 634, w: 110, h: 56, targets: ["d2"], mode: "hold", who: "any" },
    ],
    movers: [],
    hazards: [],
    goal: { x: 1080, y: 390, w: 130, h: 110 },
    plaques: [{ x: 250, y: 430, text: "ONE, THEN THE OTHER" }],
    hints: hints(
      "Each door has its own plate, and each plate must stay held.",
      "The first echo belongs in the first pit.",
      "After the first door opens, the second pit is the next echo.",
      "On the last run, drop through nothing. Both ghosts are already below.",
      "Echo in pit one, echo in pit two, then roll across both grates to the aperture."
    ),
  },
  {
    id: "echoes-only",
    name: "Echoes Only",
    chapter: 2,
    objective: "This plate ignores the living ball.",
    caption: "A hollow plate answers echoes, not you.",
    echoSeconds: 16,
    maxGhosts: 1,
    par: { ghosts: 1, seconds: 10 },
    spawn: { x: 130, y: restY(640) },
    ghostSolid: false,
    solids: [...shell(), { id: "floor", x: 0, y: 640, w: W, h: 80 }],
    doors: [{ id: "d1", x: 860, y: 28, w: 40, h: 612, logic: "or" }],
    plates: [
      { id: "p1", x: 380, y: 584, w: 170, h: 56, targets: ["d1"], mode: "hold", who: "ghost" },
    ],
    movers: [],
    hazards: [],
    goal: { x: 1060, y: 500, w: 140, h: 140 },
    plaques: [{ x: 390, y: 548, text: "ECHO" }],
    hints: hints(
      "Standing on this plate yourself does nothing.",
      "The mark on the plate is an echo, not a solid dot.",
      "Echo while you are on it. Your ghost can press what you cannot.",
      "Then leave the plate and use the door your ghost holds.",
      "Stop on the hollow plate, Echo, and pass the door once your ghost is standing there."
    ),
  },
  {
    id: "at-once",
    name: "At Once",
    chapter: 2,
    objective: "The door wants you and an echo together.",
    caption: "A solid dot means the plate wants the living ball.",
    echoSeconds: 16,
    maxGhosts: 2,
    par: { ghosts: 1, seconds: 12 },
    spawn: { x: 100, y: restY(520) },
    ghostSolid: false,
    solids: [
      ...shell(),
      { id: "left", x: 0, y: 520, w: 200, h: 200 },
      { id: "grate-p1", x: 200, y: 520, w: 140, h: 30, grate: true },
      { id: "right", x: 340, y: 520, w: 940, h: 200 },
      { id: "pit", x: 200, y: 688, w: 140, h: 32 },
    ],
    doors: [{ id: "d1", x: 980, y: 28, w: 40, h: 492, logic: "and-latch" }],
    plates: [
      { id: "p1", x: 214, y: 634, w: 112, h: 56, targets: ["d1"], mode: "hold", who: "any" },
      { id: "pNow", x: 680, y: 464, w: 160, h: 56, targets: ["d1"], mode: "hold", who: "present" },
    ],
    movers: [],
    hazards: [],
    goal: { x: 1100, y: 400, w: 120, h: 120 },
    plaques: [{ x: 690, y: 430, text: "YOU" }],
    hints: hints(
      "This door latches only when every linked plate is active together.",
      "The pit can be held by an echo. The marked plate cannot.",
      "Leave a ghost in the pit, then stand on the plate with the solid dot.",
      "Once the door latches, it stays open. You can leave the plate.",
      "Echo in the pit. On the next run, stand on the living plate until the door locks open, then go through."
    ),
  },
  {
    id: "a-short-while",
    name: "A Short While",
    chapter: 3,
    objective: "The door opens, then it forgets.",
    caption: "A pulse plate fires once. It will not wait for you.",
    echoSeconds: 14,
    maxGhosts: 2,
    par: { ghosts: 1, seconds: 8 },
    spawn: { x: 620, y: restY(640) },
    ghostSolid: false,
    solids: [
      ...shell(),
      { id: "floor", x: 0, y: 640, w: W, h: 80 },
      { id: "stop", x: 28, y: 520, w: 20, h: 120 },
    ],
    doors: [{ id: "d1", x: 1040, y: 28, w: 40, h: 612, logic: "or" }],
    plates: [
      {
        id: "p1",
        x: 120,
        y: 584,
        w: 150,
        h: 56,
        targets: ["d1"],
        mode: "pulse",
        duration: 1.45,
        who: "any",
      },
    ],
    movers: [],
    hazards: [],
    goal: { x: 1130, y: 500, w: 100, h: 140 },
    plaques: [{ x: 130, y: 548, text: "BRIEF" }],
    hints: hints(
      "Touching the plate opens the door only for a moment.",
      "If you touch it yourself, you are too far from the door to arrive in time.",
      "Let an echo touch the plate while you wait on the right.",
      "Echo on the left plate, then on the next run go straight to the door and pass while it is open.",
      "Stop on the left plate and Echo. Immediately run right and slip through before the pulse ends."
    ),
  },
  {
    id: "the-ferry",
    name: "The Ferry",
    chapter: 3,
    objective: "The platform moves only while the plate is held.",
    caption: "Something has to stay behind, or the ferry sleeps.",
    echoSeconds: 18,
    maxGhosts: 2,
    par: { ghosts: 1, seconds: 14 },
    spawn: { x: 300, y: restY(600) },
    ghostSolid: false,
    solids: [
      ...shell(),
      { id: "left", x: 0, y: 600, w: 500, h: 120 },
      { id: "right", x: 860, y: 600, w: 420, h: 120 },
      { id: "pit-floor", x: 520, y: 700, w: 320, h: 20 },
    ],
    doors: [],
    plates: [
      { id: "p1", x: 70, y: 544, w: 150, h: 56, targets: [], mode: "hold", who: "any" },
    ],
    movers: [
      {
        id: "ferry",
        x: 440,
        y: 600,
        w: 240,
        h: 32,
        axis: "x",
        distance: 300,
        period: 360,
        requires: "p1",
      },
    ],
    hazards: [{ x: 530, y: 660, w: 300, h: 60 }],
    goal: { x: 1040, y: 470, w: 150, h: 130 },
    plaques: [{ x: 80, y: 508, text: "STAY" }],
    hints: hints(
      "The platform does not move until the plate is held.",
      "If you leave the plate, the ferry stops.",
      "Echo on the plate. Your ghost keeps the ferry awake.",
      "Wait at the lip, step on when the platform is there, and let it carry you. Do not outrun it.",
      "Echo on the left plate. Ride the platform without holding right the whole way, then walk off onto the far floor."
    ),
  },
  {
    id: "late-arrival",
    name: "Late Arrival",
    chapter: 3,
    objective: "The door opens late, on purpose.",
    caption: "A delay plate remembers the touch and answers later.",
    echoSeconds: 16,
    maxGhosts: 2,
    par: { ghosts: 1, seconds: 10 },
    spawn: { x: 640, y: restY(640) },
    ghostSolid: false,
    solids: [...shell(), { id: "floor", x: 0, y: 640, w: W, h: 80 }],
    doors: [{ id: "d1", x: 1060, y: 28, w: 40, h: 612, logic: "or" }],
    plates: [
      {
        id: "p1",
        x: 90,
        y: 584,
        w: 150,
        h: 56,
        targets: ["d1"],
        mode: "delay",
        delay: 1.15,
        duration: 1.15,
        who: "any",
      },
    ],
    movers: [],
    hazards: [],
    goal: { x: 1140, y: 500, w: 90, h: 140 },
    plaques: [{ x: 100, y: 548, text: "LATER" }],
    hints: hints(
      "This plate does not open the door immediately.",
      "If you run from the plate to the door yourself, the moment has already passed.",
      "An echo can touch the plate while you wait at the door.",
      "Be at the door before the delayed pulse arrives, and go through while it lasts.",
      "Echo on the far-left plate. On the next run, wait against the door until it opens, then pass."
    ),
  },
  {
    id: "the-oath",
    name: "The Oath",
    chapter: 4,
    objective: "Leave someone below. Take the spring.",
    caption: "The spring keeps your sideways speed.",
    echoSeconds: 16,
    maxGhosts: 2,
    par: { ghosts: 1, seconds: 12 },
    spawn: { x: 100, y: restY(520) },
    ghostSolid: false,
    solids: [
      ...shell(),
      { id: "left", x: 0, y: 520, w: 180, h: 200 },
      { id: "grate-p1", x: 180, y: 520, w: 130, h: 30, grate: true },
      { id: "mid", x: 310, y: 520, w: 200, h: 200 },
      { id: "spring", x: 510, y: 520, w: 150, h: 200, surface: "spring", launch: 1120 },
      { id: "low", x: 660, y: 520, w: 620, h: 200 },
      { id: "ledge", x: 720, y: 300, w: 532, h: 26 },
      { id: "pit", x: 180, y: 688, w: 130, h: 32 },
    ],
    doors: [{ id: "d1", x: 390, y: 28, w: 40, h: 492, logic: "or" }],
    plates: [
      { id: "p1", x: 192, y: 634, w: 106, h: 56, targets: ["d1"], mode: "hold", who: "any" },
    ],
    movers: [],
    hazards: [],
    goal: { x: 1080, y: 200, w: 140, h: 100 },
    plaques: [{ x: 520, y: 480, text: "KEEP YOUR SPEED" }],
    hints: hints(
      "The aperture is on the high ledge. The spring is the only way up.",
      "The spring is behind the door, and the door wants the pit.",
      "Echo in the pit so you are free to take the spring at a run.",
      "Hold right as you cross the spring. If you miss, roll back and try again. Your ghost is still in the pit.",
      "Drop into the pit and Echo. Then sprint across the spring and land on the high ledge."
    ),
  },
  {
    id: "black-ice",
    name: "Black Ice",
    chapter: 4,
    objective: "Let the ice carry an echo to the plate.",
    caption: "Ice keeps what you give it. Commit before you slide.",
    echoSeconds: 14,
    maxGhosts: 2,
    par: { ghosts: 1, seconds: 10 },
    spawn: { x: 720, y: restY(640) },
    ghostSolid: false,
    solids: [
      ...shell(),
      { id: "ice", x: 0, y: 640, w: 430, h: 80, surface: "ice" },
      { id: "floor", x: 430, y: 640, w: 850, h: 80 },
    ],
    doors: [{ id: "d1", x: 1020, y: 28, w: 40, h: 612, logic: "or" }],
    plates: [
      { id: "p1", x: 36, y: 584, w: 170, h: 56, targets: ["d1"], mode: "hold", who: "any" },
    ],
    movers: [],
    hazards: [],
    goal: { x: 1120, y: 500, w: 110, h: 140 },
    plaques: [{ x: 80, y: 548, text: "SLIDE" }],
    hints: hints(
      "The left floor is ice. You will not stop where you let go.",
      "The plate is against the far left wall.",
      "Slide into it, wait until you settle, then Echo.",
      "Your ghost repeats the slide and holds the plate. You take the dry path on the right.",
      "Hold left until you rest on the plate, Echo, then run right through the door."
    ),
  },
  {
    id: "three-voices",
    name: "Three Voices",
    chapter: 5,
    objective: "Three pits. Three doors. One path.",
    caption: "You are building a choir. Each voice keeps a single note.",
    echoSeconds: 20,
    maxGhosts: 3,
    par: { ghosts: 3, seconds: 12 },
    spawn: { x: 80, y: restY(470) },
    ghostSolid: false,
    solids: [
      ...shell(),
      { id: "s0", x: 0, y: 470, w: 150, h: 250 },
      { id: "grate-p1", x: 150, y: 470, w: 110, h: 30, grate: true },
      { id: "s1", x: 260, y: 470, w: 160, h: 250 },
      { id: "grate-p2", x: 420, y: 470, w: 110, h: 30, grate: true },
      { id: "s2", x: 530, y: 470, w: 160, h: 250 },
      { id: "grate-p3", x: 690, y: 470, w: 110, h: 30, grate: true },
      { id: "s3", x: 800, y: 470, w: 480, h: 250 },
      { id: "pit1", x: 150, y: 688, w: 110, h: 32 },
      { id: "pit2", x: 420, y: 688, w: 110, h: 32 },
      { id: "pit3", x: 690, y: 688, w: 110, h: 32 },
    ],
    doors: [
      { id: "d1", x: 320, y: 28, w: 34, h: 442, logic: "or" },
      { id: "d2", x: 580, y: 28, w: 34, h: 442, logic: "or" },
      { id: "d3", x: 920, y: 28, w: 34, h: 442, logic: "or" },
    ],
    plates: [
      { id: "p1", x: 158, y: 634, w: 94, h: 56, targets: ["d1"], mode: "hold", who: "any" },
      { id: "p2", x: 428, y: 634, w: 94, h: 56, targets: ["d2"], mode: "hold", who: "any" },
      { id: "p3", x: 698, y: 634, w: 94, h: 56, targets: ["d3"], mode: "hold", who: "any" },
    ],
    movers: [],
    hazards: [],
    goal: { x: 1080, y: 360, w: 130, h: 110 },
    plaques: [{ x: 40, y: 430, text: "I  II  III" }],
    hints: hints(
      "Every door needs its own echo. None of them toggle.",
      "The pits are in order. The doors are in order.",
      "Drop, Echo, advance, drop again.",
      "On the last run the grates are a road, not a trap.",
      "Fill the three pits in order, then roll across all three grates to the aperture."
    ),
  },
  {
    id: "duet",
    name: "Duet",
    chapter: 6,
    objective: "Both echoes. Neither of them is you.",
    caption: "This door listens for two echoes at the same time.",
    echoSeconds: 16,
    maxGhosts: 3,
    par: { ghosts: 2, seconds: 12 },
    spawn: { x: 100, y: restY(500) },
    ghostSolid: false,
    solids: [
      ...shell(),
      { id: "s0", x: 0, y: 500, w: 220, h: 220 },
      { id: "grate-p1", x: 220, y: 500, w: 130, h: 30, grate: true },
      { id: "s1", x: 350, y: 500, w: 250, h: 220 },
      { id: "grate-p2", x: 600, y: 500, w: 130, h: 30, grate: true },
      { id: "s2", x: 730, y: 500, w: 550, h: 220 },
      { id: "pit1", x: 220, y: 688, w: 130, h: 32 },
      { id: "pit2", x: 600, y: 688, w: 130, h: 32 },
    ],
    doors: [{ id: "d1", x: 980, y: 28, w: 40, h: 472, logic: "and" }],
    plates: [
      { id: "p1", x: 232, y: 634, w: 106, h: 56, targets: ["d1"], mode: "hold", who: "ghost" },
      { id: "p2", x: 612, y: 634, w: 106, h: 56, targets: ["d1"], mode: "hold", who: "ghost" },
    ],
    movers: [],
    hazards: [],
    goal: { x: 1120, y: 390, w: 110, h: 110 },
    plaques: [{ x: 740, y: 460, text: "BOTH" }],
    hints: hints(
      "Hollow plates ignore you, even if you fall on them.",
      "The door needs both plates held, not one then the other.",
      "Two echoes can hold both pits while you stay above.",
      "Do not drop on the last run.",
      "Echo in each pit, then roll over both grates. The door opens while both ghosts remain below."
    ),
  },
  {
    id: "a-place-to-stand",
    name: "A Place to Stand",
    chapter: 7,
    objective: "Your echo can be the step you are missing.",
    caption: "Echoes are solid here. You can stand on a past self.",
    echoSeconds: 14,
    maxGhosts: 2,
    par: { ghosts: 1, seconds: 10 },
    spawn: { x: 180, y: restY(640) },
    ghostSolid: true,
    solids: [
      ...shell(),
      { id: "floor", x: 0, y: 640, w: W, h: 80 },
      { id: "dais", x: 900, y: 618, w: 352, h: 102 },
    ],
    doors: [],
    plates: [],
    movers: [],
    hazards: [],
    goal: { x: 1040, y: 490, w: 170, h: 128 },
    plaques: [{ x: 200, y: 590, text: "STEP" }],
    hints: hints(
      "The dais is too high to roll onto.",
      "In this room, echoes do not phase. They take up space.",
      "Leave an echo against the face of the dais.",
      "On the next run, roll up over your ghost and onto the dais.",
      "Stop touching the dais and Echo. Then take a run at your ghost and cross onto the platform."
    ),
  },
  {
    id: "downstream",
    name: "Downstream",
    chapter: 8,
    objective: "The second echo can only cross after the first is keeping the ferry awake.",
    caption: "Record the ferry's keeper before anyone tries to ride.",
    echoSeconds: 20,
    maxGhosts: 3,
    par: { ghosts: 2, seconds: 14 },
    spawn: { x: 250, y: restY(600) },
    ghostSolid: false,
    solids: [
      ...shell(),
      { id: "left", x: 0, y: 600, w: 460, h: 120 },
      { id: "right", x: 880, y: 600, w: 400, h: 120 },
      { id: "pit-floor", x: 480, y: 700, w: 380, h: 20 },
    ],
    doors: [{ id: "d1", x: 1120, y: 28, w: 36, h: 572, logic: "or" }],
    plates: [
      { id: "p1", x: 60, y: 544, w: 140, h: 56, targets: [], mode: "hold", who: "any" },
      { id: "p2", x: 940, y: 544, w: 120, h: 56, targets: ["d1"], mode: "hold", who: "any" },
    ],
    movers: [
      {
        id: "ferry",
        x: 380,
        y: 600,
        w: 260,
        h: 32,
        axis: "x",
        distance: 360,
        period: 360,
        requires: "p1",
      },
    ],
    hazards: [{ x: 500, y: 655, w: 360, h: 65 }],
    goal: { x: 1180, y: 480, w: 70, h: 120 },
    plaques: [{ x: 70, y: 508, text: "FIRST" }],
    hints: hints(
      "The ferry sleeps until the left plate is held.",
      "The far plate opens the aperture door, but someone has to stay on it.",
      "If you ride before anyone is holding the left plate, the ferry will not be there. Erase that echo.",
      "Echo one: the left plate. Echo two: ride across and stop on the far plate.",
      "Keep a ghost on the left plate, park a second ghost on the far plate, then ride across yourself and use the door."
    ),
  },
  {
    id: "the-core",
    name: "The Core",
    chapter: 9,
    objective: "Three echoes hold the chord. You are the last note.",
    caption: "The last door opens only when an echo and you arrive together.",
    echoSeconds: 22,
    maxGhosts: 4,
    par: { ghosts: 3, seconds: 14 },
    spawn: { x: 70, y: restY(470) },
    ghostSolid: false,
    solids: [
      ...shell(),
      { id: "s0", x: 0, y: 470, w: 140, h: 250 },
      { id: "grate-p1", x: 140, y: 470, w: 100, h: 30, grate: true },
      { id: "s1", x: 240, y: 470, w: 150, h: 250 },
      { id: "grate-p2", x: 390, y: 470, w: 100, h: 30, grate: true },
      { id: "s2", x: 490, y: 470, w: 150, h: 250 },
      { id: "grate-p3", x: 640, y: 470, w: 100, h: 30, grate: true },
      { id: "s3", x: 740, y: 470, w: 540, h: 250 },
      { id: "pit1", x: 140, y: 688, w: 100, h: 32 },
      { id: "pit2", x: 390, y: 688, w: 100, h: 32 },
      { id: "pit3", x: 640, y: 688, w: 100, h: 32 },
    ],
    doors: [
      { id: "d1", x: 290, y: 28, w: 32, h: 442, logic: "or" },
      { id: "d2", x: 540, y: 28, w: 32, h: 442, logic: "or" },
      { id: "d3", x: 1040, y: 28, w: 32, h: 442, logic: "and-latch" },
    ],
    plates: [
      { id: "p1", x: 148, y: 634, w: 84, h: 56, targets: ["d1"], mode: "hold", who: "any" },
      { id: "p2", x: 398, y: 634, w: 84, h: 56, targets: ["d2"], mode: "hold", who: "any" },
      { id: "p3", x: 648, y: 634, w: 84, h: 56, targets: ["d3"], mode: "hold", who: "any" },
      { id: "pNow", x: 820, y: 414, w: 140, h: 56, targets: ["d3"], mode: "hold", who: "present" },
    ],
    movers: [],
    hazards: [],
    goal: { x: 1120, y: 350, w: 110, h: 120 },
    plaques: [{ x: 830, y: 390, text: "NOW" }],
    hints: hints(
      "The first two doors are holds. The last door is a chord.",
      "Three pits, in order, the way the choir was built.",
      "The last plate, marked with a solid dot, will not answer a ghost.",
      "Stand on it while the third echo is in the pit. The door latches. Then you may leave the plate.",
      "Fill the three pits. On the final run, stand on the living plate until the last door locks open, and enter the core."
    ),
  },
];

export function levelById(id) {
  return levels.find((level) => level.id === id) || null;
}

export function nextLevel(id) {
  const index = levels.findIndex((level) => level.id === id);
  if (index < 0 || index >= levels.length - 1) return null;
  return levels[index + 1];
}
